description: Prepares the repo for a CI job

name: Prepare

runs:
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Dependencies
      id: npm-ci
      run: npm ci
      shell: bash

  using: composite
